<center> <h1 style='color:yellow;'> Cours 11 : Problème de Regression  </h1> </center>

CRIM - taux de criminalité par habitant par ville
ZN - proportion de terrains résidentiels zonés pour des lots de plus de 25 000 pi.ca.
INDUS - proportion d'acres de superficie commerciale non commerciale par ville.
CHAS - Variable fictive de la rivière Charles (1 si la zone est délimitée par la rivière ; 0 sinon)
NOX - concentration en oxydes nitriques (parties pour 10 millions)
RM - nombre moyen de pièces par logement
ÂGE - proportion de logements occupés par leur propriétaire construits avant 1940
DIS - distances pondérées vers cinq centres d'emploi de Boston
RAD - indice d'accessibilité aux autoroutes radiales
TAXE - taux d'imposition foncière sur la valeur totale par tranche de 10 000 $
PTRATIO - ratio élèves-enseignant par ville
B - 1000(Bk - 0,63)^2 où Bk est la proportion de Noirs par ville
LSTAT - % de statut inférieur de la population
MEDV - Valeur médiane des maisons occupées par leur propriétaire en milliers de dollars

In [1]:
from pandas import read_csv
import pandas as pd
try:
           
    fichier='housing.csv'
    col=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAXE','PTRATIO','B','LSTAT','MEDV']
    data=read_csv(fichier,delim_whitespace=True,names=col)
    pd.set_option('display.max_columns',None)
    pd.set_option('display.float_format','{:.2f}'.format)
    print(data)
except:
    print('Erreur de lecture du fichier')

Erreur de lecture du fichier

C:\Users\fayem\AppData\Local\Temp\ipykernel_14128\875294920.py:7: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data=read_csv(fichier,delim_whitespace=True,names=col)

In [2]:
data.describe()

NameError: name 'data' is not defined

In [ ]:
data.shape

(506, 14)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAXE     506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [ ]:
data.corr()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAXE,PTRATIO,B,LSTAT,MEDV
CRIM,1.00,-0.20,0.41,-0.06,0.42,-0.22,0.35,-0.38,0.63,0.58,0.29,-0.39,0.46,-0.39
ZN,-0.20,1.00,-0.53,-0.04,-0.52,0.31,-0.57,0.66,-0.31,-0.31,-0.39,0.18,-0.41,0.36
INDUS,0.41,-0.53,1.00,0.06,0.76,-0.39,0.64,-0.71,0.60,0.72,0.38,-0.36,0.60,-0.48
CHAS,-0.06,-0.04,0.06,1.00,0.09,0.09,0.09,-0.10,-0.01,-0.04,-0.12,0.05,-0.05,0.18
NOX,0.42,-0.52,0.76,0.09,1.00,-0.30,0.73,-0.77,0.61,0.67,0.19,-0.38,0.59,-0.43
RM,-0.22,0.31,-0.39,0.09,-0.30,1.00,-0.24,0.21,-0.21,-0.29,-0.36,0.13,-0.61,0.70
AGE,0.35,-0.57,0.64,0.09,0.73,-0.24,1.00,-0.75,0.46,0.51,0.26,-0.27,0.60,-0.38
DIS,-0.38,0.66,-0.71,-0.10,-0.77,0.21,-0.75,1.00,-0.49,-0.53,-0.23,0.29,-0.50,0.25
RAD,0.63,-0.31,0.60,-0.01,0.61,-0.21,0.46,-0.49,1.00,0.91,0.46,-0.44,0.49,-0.38
TAXE,0.58,-0.31,0.72,-0.04,0.67,-0.29,0.51,-0.53,0.91,1.00,0.46,-0.44,0.54,-0.47
PTRATIO,0.29,-0.39,0.38,-0.12,0.19,-0.36,0.26,-0.23,0.46,0.46,1.00,-0.18,0.37,-0.51
B,-0.39,0.18,-0.36,0.05,-0.38,0.13,-0.27,0.29,-0.44,-0.44,-0.18,1.00,-0.37,0.33
LSTAT,0.46,-0.41,0.60,-0.05,0.59,-0.61,0.60,-0.50,0.49,0.54,0.37,-0.37,1.00,-0.74
MEDV,-0.39,0.36,-0.48,0.18,-0.43,0.70,-0.38,0.25,-0.38,-0.47,-0.51,0.33,-0.74,1.00

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

dataML=data.values

x=dataML[:,:-1]
y=dataML[:,-1]

test=0.2
seed=11

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=test,random_state=seed)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

MAE=mean_absolute_error(y_test,y_pred)
MSE=mean_squared_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)

print(f'MAE : {round(MAE,4)}')
print(f'MSE : {round(MSE,4)}')
print(f'R2 : {round(R2*100,4)} %')

MAE : 3.5673
MSE : 26.9448
R2 : 68.595 %

In [ ]:
import numpy as np
maison=[0.22489,12.50,7.870,0,0.5240,6.3770,94.30,6.3467,5,311.0,15.20,392.52,20.45]
maison_array=np.array([maison])
pred=model.predict(maison_array)[0]
print(f'Prix : {pred} ---- [{pred-MAE},{pred+MAE}]')

Prix : 19.42969910218886 ---- [15.862373083192063,22.997025121185658]

# Evaluation comparative

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

dataML=data.values

x=dataML[:,:-1]
y=dataML[:,-1]

test=0.2
seed=11
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=test,random_state=seed)

metrics=[]
metrics.append(('MAE',mean_absolute_error))
metrics.append(('MSE',mean_squared_error))
metrics.append(('R2',r2_score))

models=[]
models.append(('LR',LinearRegression()))
models.append(('Lasso',Lasso()))
models.append(('Ridge',Ridge()))
models.append(('D-Tree',DecisionTreeRegressor()))
models.append(('KNN-R',KNeighborsRegressor(n_neighbors=15)))
models.append(('SVM-R',SVR()))

for metric_name, metric in metrics:
    print('')
    # Fit the model
    model.fit(x_train, y_train)
    
    # Predict on the test set
    y_pred = model.predict(x_test)
    
    # Evaluate the model using the specified metrics
    print(f"Results for {name}:")
    for metric_name, metric_func in metrics:
        score = metric_func(y_test, y_pred)
        print(f"{metric_name}: {score:.4f}")
    print("-" * 30)

NameError: name 'name' is not defined

## Cours 12

## 1-Valitation croiser

In [ ]:
from sklearn.model_selection import cross_validate,KFold, cross_val_predict
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

dataML=data.values

x=dataML[:,:-1]
y=dataML[:,-1]

test=0.2
seed=11

cv = KFold(n_splits = 10, shuffle = True, random_state =seed)

model=LinearRegression()

y_pred=cross_val_predict(model, x, y,cv=cv)

MAE=mean_absolute_error(y,y_pred)
MSE=mean_squared_error(y,y_pred)
R2=r2_score(y,y_pred)

print(f'MAE : {round(MAE,4)}')
print(f'MSE : {round(MSE,4)}')
print(f'R2 : {round(R2*100,4)} %')

MAE : 3.4057
MSE : 24.0621
R2 : 71.497 %

# 1-Validation croisée

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR


from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Binarizer

dataML=data.values

x=dataML[:,:-1]
y=dataML[:,-1]

# StandardScaler------------------------
scaler=StandardScaler()
x_train_scaler = scaler.fit_transform(x_train)
x_test_scaler = scaler.transform(x_test)

test=0.2
seed=11
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=test,random_state=seed)

metrics=[]
metrics.append(('MAE',mean_absolute_error))
metrics.append(('MSE',mean_squared_error))
metrics.append(('R2',r2_score))

models=[]
models.append(('LR',LinearRegression()))
models.append(('Lasso',Lasso()))
models.append(('Ridge',Ridge()))
models.append(('D-Tree',DecisionTreeRegressor()))
models.append(('KNN-R',KNeighborsRegressor(n_neighbors=15)))
models.append(('SVM-R',SVR()))

for metric_name, metric in metrics:
    print(f'{metric_name}\n------\n')
    for model_name, model in models:
        model.fit(x_train_scaler,y_train)
        y_pred = model.predict(x_test_scaler)
        error = metric(y_test,y_pred)
        print(f'{model_name}: {round(error,3)}')